// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFDrAtdcs3aGERwYxcH1V-hVMsS0hpVrA',
    appId: '1:544198376722:web:d0224098f4b4a4d8b887cb',
    messagingSenderId: '544198376722',
    projectId: 'chit-chat-app-9bf0c',
    authDomain: 'chit-chat-app-9bf0c.firebaseapp.com',
    storageBucket: 'chit-chat-app-9bf0c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnYpBLrcdhDxfMQf5X3pBC6-FDBXnffp8',
    appId: '1:544198376722:android:18d4630603723a64b887cb',
    messagingSenderId: '544198376722',
    projectId: 'chit-chat-app-9bf0c',
    storageBucket: 'chit-chat-app-9bf0c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJwuOsIgjeH25E1xSjD1pdtf0qk_k99tA',
    appId: '1:544198376722:ios:2e850e9a6be9affab887cb',
    messagingSenderId: '544198376722',
    projectId: 'chit-chat-app-9bf0c',
    storageBucket: 'chit-chat-app-9bf0c.firebasestorage.app',
    iosBundleId: 'com.akshat.minimalchatapp.minimalChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJwuOsIgjeH25E1xSjD1pdtf0qk_k99tA',
    appId: '1:544198376722:ios:2e850e9a6be9affab887cb',
    messagingSenderId: '544198376722',
    projectId: 'chit-chat-app-9bf0c',
    storageBucket: 'chit-chat-app-9bf0c.firebasestorage.app',
    iosBundleId: 'com.akshat.minimalchatapp.minimalChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFDrAtdcs3aGERwYxcH1V-hVMsS0hpVrA',
    appId: '1:544198376722:web:bf9b500c5d0c8c09b887cb',
    messagingSenderId: '544198376722',
    projectId: 'chit-chat-app-9bf0c',
    authDomain: 'chit-chat-app-9bf0c.firebaseapp.com',
    storageBucket: 'chit-chat-app-9bf0c.firebasestorage.app',
  );
}
